### ISSUE TITLE
Проблема при компиляции pinba2

### ISSUE THREAD

**Issue by gerbert000** [badoo/pinba2#22]
Здравствуйте.
Подскажите в чем может быть проблема. Есть debian 8.11, пытаюсь скомпилировать pinba2 по инструкции, но на этапе "make" получаю следующие офибки:
----------------------
In file included from globals.cpp:15:0:
../include/pinba/dictionary.h:131:72: error: expected ‘,’ before ‘)’ token
     static_assert(std::is_nothrow_move_constructible<nameword_t>::value);
                                                                        ^
../include/pinba/dictionary.h:131:72: error: expected string-literal before ‘)’ token
../include/pinba/dictionary.h: In member function ‘const nameword_dictionary_t::nameword_t* nameword_dictionary_t::insert_with_external_locking(meow::str_ref)’:
../include/pinba/dictionary.h:219:2: error: could not convert ‘{word_id, pinba::hash_number<unsigned int>(((uint32_t)word_id)), word_hash}’ from ‘<brace-enclosed initializer list>’ to ‘nameword_dictionary_t::nameword_t’
  };
  ^
globals.cpp: At global scope:
globals.cpp:207:90: error: expected ‘,’ or ‘;’ before ‘PINBA_VCS_FULL_HASH’
  volatile char const pinba_version_info[] = "pinba_version_info " PINBA_VERSION " git: " PINBA_VCS_FULL_HASH " modified: " PINBA_VCS_WC_MODIFIED;
                                                                                          ^
Makefile:580: ошибка выполнения рецепта для цели «globals.o»
make[2]: *** [globals.o] Ошибка 1
make[2]: выход из каталога «/home/vladimir/pinba/pinba2-master/src»
Makefile:483: ошибка выполнения рецепта для цели «all-recursive»
make[1]: *** [all-recursive] Ошибка 1
make[1]: выход из каталога «/home/vladimir/pinba/pinba2-master»
Makefile:372: ошибка выполнения рецепта для цели «all»
make: *** [all] Ошибка 2
----------------------

Подскажите, что и где подправить. Спасибо.

**Comment by anton-povarov** [comment]
Я бы ванговал старый gcc.
И показывайте уже полный лог сборки, что и как делаетею

**Comment by mekras** [comment]
Проблема возникает если отсутствует папка `.git`, например, если для сборки используется архив https://github.com/badoo/pinba2/archive/v2.5.0.tar.gz

**Comment by mekras** [comment]
Отвечает за это `autorevision.sh`.

**Comment by anton-povarov** [comment]
О, спасибо, проблему понял.
Как починить "по красоте" сходу не понятно (без того, чтобы ручками эту информацию каждый раз не комитить).

Как workaround предлагаю клонировать конкретный git tag с нужной версией.

**Comment by anton-povarov** [comment]
Вот такой патч фиксит компиляцию хотя бы. Проставляя нужные переменные пустыми.
Как вам @mekras @gerbert000 ?

**Comment by mekras** [comment]
Ну я уже сделал через git clone. Сейчас попробовал собрать из архива master — порядок, собралось.

**Comment by anton-povarov** [comment]
OK, тогда считаем, что fixed in master.
Сделаю релиз 2.6 с этим изменением.
