### ISSUE TITLE
Ошибки при сборке.

### ISSUE THREAD

**Issue by zakachkin** [badoo/pinba2#24]
/bin/bash ../libtool --preserve-dup-deps  --tag=CXX   --mode=link g++ -std=c++14 -fno-rtti  -pthread -Wformat -Wformat-security -Werror -Wno-unused -Wno-unused-parameter -Wno-unused-variable -Wno-missing-field-initializers -Wno-parentheses -fno-omit-frame-pointer -fPIC -DPIC -D_GNU_SOURCE -D_POSIX_SOURCE -maes -msse4 -msse4.2 -O3 -ffast-math -ggdb3 -mtune=native -I../third_party -I../third_party/robin-map/include -pthread -I/usr/local/include -I/usr/src/meow/ -I/usr/include -I/usr -I../include   -flto
-lrt -ldl -rdynamic  -lanl -o pinba2 main.o libpinba2.a ../third_party/t1ha/libt1ha.a /usr/local/lib/libnanomsg.a
libtool: link: g++ -std=c++14 -fno-rtti -pthread -Wformat -Wformat-security -Werror -Wno-unused -Wno-unused-parameter -Wno-unused-variable -Wno-missing-field-initializers -Wno-parentheses -fno-omit-frame-pointer -fPIC -DPIC -D_GNU_SOURCE -D_POSIX_SOURCE -maes -msse4 -msse4.2 -O3 -ffast-math -ggdb3 -mtune=native -I../third_party -I../third_party/robin-map/include -pthread -I/usr/local/include -I/usr/src/meow/ -I/usr/include -I/usr -I../include -flto -rdynamic -o pinba2 main.o  -lrt -ldl -lanl libpinba2.a ../third_party/t1ha/libt1ha.a /usr/local/lib/libnanomsg.a -pthread
libpinba2.a(os_symbols.o): In function `(anonymous namespace)::aux::pinba_os_symbols_impl_t::~pinba_os_symbols_impl_t()':
/usr/src/pinba2/src/os_symbols.cpp:27: undefined reference to `dlclose'
libpinba2.a(os_symbols.o): In function `pinba_os_symbols___init(pinba_globals_t*)':
/usr/src/pinba2/src/os_symbols.cpp:17: undefined reference to `dlopen'
/usr/src/pinba2/src/os_symbols.cpp:19: undefined reference to `dlerror'
libpinba2.a(os_symbols.o): In function `(anonymous namespace)::aux::pinba_os_symbols_impl_t::resolve(meow::string_ref<char const>)':
/usr/src/pinba2/src/os_symbols.cpp:42: undefined reference to `dlerror'
/usr/src/pinba2/src/os_symbols.cpp:44: undefined reference to `dlsym'
/usr/src/pinba2/src/os_symbols.cpp:45: undefined reference to `dlerror'
libpinba2.a(os_symbols.o): In function `(anonymous namespace)::aux::pinba_os_symbols_impl_t::~pinba_os_symbols_impl_t()':
/usr/src/pinba2/src/os_symbols.cpp:27: undefined reference to `dlclose'
collect2: error: ld returned 1 exit status
Makefile:543: recipe for target 'pinba2' failed
make[2]: *** [pinba2] Error 1
make[2]: Leaving directory '/usr/src/pinba2/src'
Makefile:494: recipe for target 'all-recursive' failed

make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory '/usr/src/pinba2'
Makefile:384: recipe for target 'all' failed
make: *** [all] Error 2

No` LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 18.04.5 LTS
Release:        18.04
Codename:       bionic

Mariadb 10.2

Не могу понять в чём дело. Помогите пожалуйста.

**Comment by anton-povarov** [comment]
Это странно, `dlclose` - это функция, которая должна лежать в libdl, которую при сборке мы просим подключить флагом `-ldl`.

Возможно надо поиграться в порядком указания библиотек, т.к. линкеры могут быть странными.
Сборка и использование в докере не подходит?

**Comment by anton-povarov** [comment]
Покажите еще вывод `g++ --version` плз.

**Comment by zakachkin** [comment]
g++ --version
g++ (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
Copyright (C) 2017 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

**Comment by zakachkin** [comment]
А что где включить надо? поясните пожалуйста

**Comment by zakachkin** [comment]
Докер не наш вариант.. Если б можно было без геморроя я бы использовал докер

**Comment by anton-povarov** [comment]
Вот быстрофикс, кажется, что нужно лучше, но так пока тоже сойдет.

**Comment by anton-povarov** [comment]
@zakachkin ну как, работает? (этот коммит в мастере, например).

**Comment by zakachkin** [comment]
Собраться -то оно собралось только теперь вот что пишет 

```
root@server2:/usr/src/pinba2# echo "install plugin pinba soname 'libpinba_engine2.so';" | mysql -p
Enter password: 
ERROR 1126 (HY000) at line 1: Can't open shared library '/usr/lib/mysql/plugin/libpinba_engine2.so' (errno: 2, undefined symbol: my_print_error_service)
```
Что ему не нравися?

**Comment by anton-povarov** [comment]
Теоретически, тут надо дополнительно сказать `--enable-libmysqlservices` при `configure`, может заработать, а может и нет.
В почти каждой версии каждого дистрибутива для каждого из mysql/mariadb/percona, чего-нибудь кто-нибудь да сломает в способах сборки внешних плагинов ;(

**Comment by zakachkin** [comment]
Спасибо! помогло.
